import {StyleSheet} from 'react-native';
import colors from '../../components/common/colors';

const style = (width, height) =>
  StyleSheet.create({
    container: {
      height: height*0.95,
      // padding: 15,
      marginTop: 15,
      backgroundColor: colors.white_lvl_3,
    },
    // ProductView: {
    //   backgroundColor: colors.white_Bg,
    // },
    // ProductTouch: {
    //   alignSelf: 'center',
    //   // borderRadius: 15,
    //   flexDirection: 'row',
    //   alignItems: 'center',
    //   width: width,
    //   padding: 15,
    //   backgroundColor: colors.white,
    //   marginTop: 10,
    //   // marginBottom:15,
    // },
    // productImage: {
    //   width: 90,
    //   height: 90,
    //   resizeMode: 'contain',
    //   borderRadius: 10,
    // },
    // secondView: {
    //   borderLeftColor: colors.iron,
    //   borderLeftWidth: 1.5,
    //   padding: 10,
    //   marginLeft: 10,
    //   width:width*0.65,
    //   overflow:'hidden',
    //   // backgroundColor:colors.red,
    // },
    // name: {
    //   fontFamily: 'Lato-Bold',
    //   fontSize: 18,
    //   color: colors.black,
    //   lineHeight: 35,
    // },
    // desc: {
    //   fontFamily: 'Lato-Regular',
    //   fontSize: 14,
    //   color: colors.pebble,
    // },
    // bottomView: {
    //   flexDirection: 'row',
    //   justifyContent: 'space-between',
    //   alignItems: 'center',
    //   marginVertical: 5,
    // },
    // price:{
    //   fontFamily: 'Lato-Bold',
    //   fontSize: 15,
    //   color: colors.black,
    // },
    
    
    productView: {
      width: width,
      height: width * 0.45,
      marginVertical: 0.6,
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.white,
      overflow: 'hidden',
      borderRadius: 5,
    },
    productImage: {
      width: width * 0.4,
      height: height * 0.13,
      resizeMode: 'contain',
      alignSelf: 'center',
      overflow: 'hidden',
    },
    productNameView: {
      paddingHorizontal: 1.2,
      width: width * 0.545,
      height: width * 0.44,
      overflow: 'hidden',
      paddingLeft: 5,
    },
    name: {
      fontFamily: 'Lato-Bold',
      fontSize: 21,
      color: colors.black,
      lineHeight: 30,
    },
    des: {
      fontFamily: 'Lato-Regular',
      fontSize: 16,
      color: colors.black,
      lineHeight: 20,
    },
    priceView: {
      flexDirection: 'column',
      alignItems: 'center',
      marginVertical: 8,
      width: width * 0.545,
      height: width * 0.35,
      // backgroundColor:colors.green,

    },
    priceView2: {
      width: width * 0.545,
      height: width * 0.1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 8,
      // backgroundColor:colors.blue,
    },
    price: {
      fontFamily: 'Lato-Regular',
      fontSize: 28,
      color: colors.black,
    },
    cartView: {
      borderRadius: 100,
      borderColor: colors.black,
      backgroundColor:colors.golden_yellow,
      borderWidth: 0.2,
      padding: 10,
      top:10,
      left:-22,
      paddingHorizontal: 50,
      paddingVertical: 12,
    },
    cartText: {
      fontFamily: 'Lato-Regular',
      fontSize: 19,
      color: colors.black,
    },
    removeView:{
      width:35,
      height:35,
      position:'absolute',
      bottom: 10,
      right: 10,
      overflow:'hidden',
      borderRadius:15,
      backgroundColor:colors.alice_blue,
      justifyContent:'center',
      alignItems:'center',
    },
    remove:{
      width:23,
      height:23,
      resizeMode:'contain',
    },
    // cartIcon: {
    //   width: 35,
    //   height: 35,
    //   resizeMode: 'contain',
    //   marginRight: 15,
    // },
    // cartCount:{
    //   position:'absolute',
    //   right:10,
    //   top:-10,
    //   width:23,
    //   height:23,
    //   backgroundColor: colors.green,
    //   justifyContent:'center',
    //   alignItems:'center',
    //   borderRadius:10,
    //   overflow:'hidden',
    //   zIndex:9,
    // },
    // count:{
    //   color:colors.white,
    //     fontFamily:'Lato-Black',
    //     fontSize:16,
    //     textAlign:'center',
    // },
  });

export default style;